#+TITLE: Naurrnen
* Secret Origins
** Introduction
This file contains spoilers for the world of Naurrnen. What is the difference between science and magic? The difference, I believe, is far more subtle and blurry than one in our modern age might be willing to admit. Science is being able to explain phenomenon as a form of a satisfactory answer as to the what and why of what happens, and formulating that explanation as a consistent repeatable system. Magic is simply the exceptions to the known rules of science, that have not yet received an explanation of how the phenomenon fits the larger explainable scientific world. Beyond that, magic and science are hardly distinguishable. Men and women's conquest to learn more, I believe, is an infinite journey that never arrives to its destination. Given that, there will ever be both the phenomenal and noumenal.

** Gravity Mining
Gravity mining is the process of creating entirely new substances through the use of extremely strong gravitational pull, from the likes of a neutron star or black hole. The easiest manner to describe this process in the real world, is essentially, two particles are bound through quantum mechanics, and once bound, one particle is isolated in a gravity-free container, at absolute zero, and the other is flung into a neutron star or black hole. At a certain point, the linked particle is unlinked, and is something entirely different. What substance you ended up with depended entirely on the starting mass, the gravitational pull of the other particle, the link strength of the two particles, and at which stage the unlinking process begun. The linking and unlinking processes became known as "quantum linking". Because the actual matter being used matters very little, and the abundance of matter to use for the process, and even the ability to recycle the created substances, it is possible to mass produce several entirely new substances. Two of the most common substances produced are a super fuel for space travel, and metal that can withstand speed of light travel.

** Planetary Commerce
Given the distance between solar systems, it became expedient to send space stations to un-inhabitable systems for the purpose of refueling, and maintenance of cargo ships. Initially, these stations were sent to orbit various planets in these systems. Profitable enterprises would build these stations, and sell fuel, maintenance and entertainment. As demand grew for waypoints with lots of trade traffic, these stations would be expanded. Often, in many higher traffic stations, they were expanded to the size of small moons, and then the size of planets that would be relocated from a planetary orbit to a solar orbit. Thus the beginning of synthetic planetary systems. The progression was something like space station to synthetic moon, to synthetic planet. When inter-galactic trade routes extended beyond what was convenient, a less expensive alternative was formed for creating way points along the trade routes. This gave way to terraforming planets to make them habitable. It was far more economic to start a populace on a terraformed planet using incubation pods. Where literally hundreds of thousands of fertilized human and alien embryos could be nurtured and grown. Artifical intelligence had made it possible to nurture embryos that were ready to become infants in the outside world.
*** Naurrnen (Syscon 37221)
Syscon 37221 was one such planet. When the trade route dryed up, the populace was relocated and the planet abandoned. Or so it was thought. Records indicate that there were numerous pods abandoned to the AI to raise without any monitoring at all. It looks like a beaurocratic cover-up in order to avoid costly relocation of equipment. When the coverup was discovered, a recovery mission was sent in order to re-assume the hatched embryos into society, and possibly recover any equipment that might be salvageable. The system in which the planet was part of was no more. Swallowed up by a neighboring worm hole for sure, it would seem. If the planet still existed, it was unreachable, now.

** Ideas
1. Active satellites still orbiting and still self correcting orbital path, that interact with the planet, and "magical artifacts" i.e. staff that calls fire (lasers?) or nanite robots that repair tissue
2. EMP devices that are interpreted to be "anti-magical"
3. solar energy as a possible source of renewable energy
4. terraformed planet
* World
** Races
*** Primary Races
The races within Naurnnen are fairly equal. Although Elves are known for their skills in magic, music, and crafting instruments and enchanted items, that does not mean one will find elves doing hard labor, exercising what strength they have. Orcs are generally favored for that sort of labor, as they tend to be more physically suited for the task. But not every Orc is physically built for this task, as not every Elf is well suited to the arts. Their are Orcs who take an interest in magic or music, as well. They are generally not as well suited as the Elves, but that is not to say, their are not Orcs that have better ears, or eyes than many Elves, or better minds for magic. These exceptions are generally blamed on half-breeds. Half-breeding has become so common in the age of man, no one really knows for sure who is a half-breed, or if one, who might think themselves as a pure-bred, is really a fourth or fifth generation mixed breed. What separates the races more than anything are their cultural identities.
**** Anashim or Elf
***** Language
Anashim language has several dialects. The most common being that of the Hallashim.
***** Anashim Sub-races
1. High Anashim: Hallashim
2. Wood Anashim: Taurashim
3. Dark Anashim: Durashim
4. Cavern Anashim: Gathashim
***** Strengths
1. Magic
2. Art
3. Architecture
4. Music
5. Crafts
   - Magical items
   - Musical instruments
***** Pantheon
| *Anor*   | Highest father of vengeance.                    |
| *Ithil*  | Highest mother of justice. The great protector. |
| *Gladys* | Goddess of nature.                              |
| *Gurth*  | God of the underworld. Friend of the dead.      |
| *Nostia* | Goddess of fertility.                           |
**** Adama or Man
***** Language
Men's language had been historically Hallashim, as man had been the slaves of certain High Elf empires. But they did have a language of their own that differentiated them from their captors. That slave language evolved into a full-blown Adaman language or language of man. That language became known by the early third era as Malairt or "trade" language.
***** Sub-races
1. Dark man: Durama
2. Red man: Edama
3. Pale man: Palama
***** Strengths
1. Multi-purpose
2. Rational
***** Pantheon
| *Dagda*     | Highest father vengeance and justice.     |
| *Morrigaan* | Highest mother, nuture and nature.        |
| *Orown*     | God of the underworld.                    |
| *Brigid*    | Goddess of art, beauty, and fertility.    |
| *Bres*      | Man king who was exalted to the pantheon. |
**** Orpa
Known in elvish as Osunus, and to the humans as Orcs.
***** Strengths
1. Fighters
2. Manual labor
3. Crafts
   - Blacksmithing
   - Metal/ore work
***** Pantheon
| *Gadajok*  | Highest god. God of vengeance.                   |
| *Hann*     | Highest mother. Goddess of nature and fertility. |
| *Vras*     | God of the dead.                                 |
| *Beatrice* | Goddess of fertility.                            |
| *Nadgaj*   | God of war. God of combat.                       |
*** Secondary Races
**** Mochveneba
Mochveneba or "ghost people" are a minority ethnicity within Naurrnen. They are elf-like, in that they share many of the features that elven folk have, but they are well known for their physical prowness. Their skin is a deep red, with stripes. Similar to tiger stripes. In fact, legend outside the Mochveneba tribes, say they are crossbred elves with tigers. In reality, they are more than likely half-breeds. More than likely, half-elf, and half-something else. They have unusual stamina, so some speculate half-orc, though their uncommon beauty seems to indicate otherwise.

The Mochveneba tribes are religious, and perhaps to most of the civilized world, somewhat superstitious. Mochveneba are spiritual and do not generally pursue material wealth. Those that do, are coveted for their beauty and brute strength.
***** Strengths
1. Enchanting weapons and items.
2. Known for physical strength.
3. Warlike, but peace-loving.
***** Pantheon
Unknown

** Languages
*** Adaman, the trade tongue
Adaman is the (almost) universal tongue of Naurrnen. It is used amongst merchants, and mosty widely spoken in everyday communication within the Gran Imperio.
*** Hallashim, language of the Elves
** Geography
*** Gran Imperio
The human empire. Though many would argue that it is not purely human, but a truly pluralistic and inclusive society. It is an empire with a relatively strong monarchy.
*** Kingdom of Tanquende
Elven kingdom, primarilly the Hallashim (a.k.a. High Elves).
*** Vulwin Horde
Nomadic tribes of the Taurashim (Wood Elves).
*** Tribes of Nigrumia
Tribes of the Orpa (a.k.a the Orcs).
*** Dathakhian Empire
Empire of the Durashim (a.k.a Dark Elves).
*** Marches of Bounoshin
Home of the Gathashim (the Cavern Elves or Dwarves).
*** Commonwealth of Caria
Home of the Palama (Pale men, or Nords).
*** Federation of Boignia
Federation of Man (Adama).
*** Principality of Vilesia
Principality of the Durama (a.k.a dark men).
** Libraries in Naurrnen
*** Printing Press
The printing press in Naurrnen has been around for over a hundred years. Newspapers are printed and delivered throughout the Gran Imperio and the Kingdom of Ivasaar.
*** Providential Libraries
**** Weylesbury, Gran Imperio (just a few miles south of Ponte Cidade
City library, used for research by University.
**** Laurië Citime, Kingdon of Tanquende (Capital of Tanquende)
One of the oldest libraries in Naurrnen. Contains some of the oldest volumes known to civilization. There is also the largest Transcript guild within the city. The Transcript guild tries to make exact copies of the most ancient books within the library in an effort to preserve the books. They also make copies available to the printing presses, but these are considered inferior to the original books. Symbols, pictures, and sketches are of equal value to the printed word, and a book with just the printed word, contains only half the worth of the original. Lithography has been strictly prohibited within the Kingdom of Tanquende, so mass producing images in these arcane books are not currently legally possible. This also artificially inflates the value of the book copies made by the Transcript guilds.
**** Ornasion, Gran Imperio
This is the largest library in Naurrnen. It consists of a large citidel, with a castle and towers. It is primarily run by the Gran Imperio's Archivist Guild. The citidel consists of thousands of rooms deep under the surface of the city, and far into the chambers above the ground. Most of the transcriptions of the ancient books in Laurië Citime have been purchased and stored at this library.

** Metals
*** Saruleum
1. From the ancient tongue (similar to Latin), meaning "blue".
2. Color is silver with streaks of blue light
3. Primary source of magicka
4. Primary source of energy
5. Is mined
6. Sometimes used as currency, but since it is generally softer than gold, it is not ideal for coinage.

Saruleum is a soft metal and is an extremely inefficient energy source for magic, but an extremely efficient source of energy for mechanical contraptions. This means that cultures will view the resource as scarce, and better used for non-magical applications. Of course, the wizard guilds will want an unlimited supply of the resource so they can explore and learn more about magic.

*** Baruleam
A hard and heavy metal. Can be used as armor but is too heavy to make full suits of armor. Usually a plate of the metal will be used in conjunction with steel. It is most commonly used in constructs for production that need sturdy materials in order to function.

*** Steel
An allow of carbon and iron. Treasured as a hard, yet portable metal, ideally used for weapons and armor.

** Trade
*** Famous Trade Routes
**** Ponte Cidade
Ponte Cidade or "the bridge city" is the capital of Gran Imperio or "grand empire". Since the fifth century of the third age, Ponte Cidade has been the trade capital of the known world. Goods from the farthest reaches flow to and forth from Ponte Cidade. Massive trade routes flowing from east to west and from north to south. Enriching many of the towns and cities along its trade routes. Gold, rare ores, and exotic food from the south, silks and fine garments from the east, smithing and magical items from the north. Shipping goods from the west. Religion and culture also spreads across the trade routes.
