#+TITLE: Stories
* Biographies
** Scholars
*** Bayetti Falasha
Bayetti Falasha was an elven scholar, dated as far back as the early second era. She was a court scholar of the great Elven empire. She wrote many books on philosophy and poetry that are still used extensively and held in the highest regard amongst Elven folk. Bayetti is, perhaps, the best known scholar of Naurnen's ancient history. Her most famous work was called "The Ameara" or "The Ancient Ones".
* Books
** History
*** The Ancient Ones
**** Author: Bayetti Falasha
**** Date: Early second era.
* Short Stories
** Traveling Scholars
*** Ancient ruins: Observance of Ponte Cidade sscholar
There are ruins in Naurrnen that predate the first era. Strange ruins, that suggest a far more advanced society. But there is no record of who. It's like the history of our world was swallowed up in oblivion. The Ameara, the ancient ones, or ancient people, had built a civilization prior to our recorded history. What is so odd, is that the "ruins" don't look ruined at all. Just abandoned. They have mostly remained intact. Some scholars believe this mysterious race just abandoned their civilization, since there are no traces of mass destruction. While many of the remnants of the Amearans in Naurrnen have seemingly been preserved, by the magical properties their structures and artifacts contain, we have come accross many artifacts that do, indeed, decay and erode.
*** Expedition
We had been walking the entire day. We came to a clearing at the foot of the hills, before we stopped to rest a moment. I threw my sack down, pulled off my shoes, and started rubbing the bottom of my feet. The massage helped some, but did not totally quell the pain. I slipped my shoes back on, and tied the laces. I swung my sack around my shoulder, and we were off once again. As we crossed over the hill's crest, I could see the metal claws reaching out of the ground in the distance. They glimmered what looked like white gold, gleaming in the starlit sky. Blue lit veins flowing all along each claw, emanating the hidden magicka within. These were the gates of the ancient city of Ameara.
** Maiden Warrior
My hand ached from gripping so hard. Jagged rocks under the palms of my hands, were poking my skin. If I thought I would not fall, I would release the rock from my hands. Glaring downward while clinging to the side of the mountain wall, I could not see the ground. The clouds had concealed it, or it was too far down to see. I wasn't too sure which. I had no sword, or shield. Had I dropped them? It was then, that I noticed I was not wearing my leathers, but a gown. A long silk gown decorated with lace and ribbon, I was dressed for a ball, not for a fight. Yet fighting was exactly what I was doing, wasn't I? Fighting for dear life. I heard a voice far below me. It was a sweet voice of... a child? No, it sounded like Elandra. But how? She could not have survived the fall I saw her take. Yet, she still lives? I could hear her voice getting louder and louder, as if she were running up the mountain wall. It was then, that I noticed the mountain wall flying past me, the rock I was clasping had some how dislodged itself from the mountain. I was falling. Elandra's voice below me, getting louder, louder, and then suddenly getting more distant. I must have fallen past her. I tried to look down to see what might lie below me, and all I saw was darkness. I flung out of bed, dripping with sweat, and gasping for my breathe. "Another nightmare?" Galabra asked? "Thank the gods, I was only dreaming!" "Rather intensely, I might add. I haven't seen you awake sweating like you are now." "I was on the face of a cliff, hanging on for dear life. Elandra was with be, but she slipped and fell. I could not see the bottom. But I heard her voice, after she fell. She was calling out to me." "You still blame yourself for her death, don't you?" I looked right into Galabra's bright silver eyes, and told her "yes! Even after all these years, I wish it had been me to fall, and not her." Galabra's eyes softened, with a concerned look. A look full of pity, like that of a mother looking at her child who was in pain, when she could do nothing to eleviate it. "You can't keep beeting yourself up over what happened. It wasn't your fault." "No, but the gods should have taken me, not her!" "Says who? You know that comes from self-loathing, and not from your love for Elandra, as great as that is." I broke down and started crying.

My leathers were on top of the dresser, where Galabra had put them, and my sword and shield leaning against the wall beside the dresser. "Good morning, Renna, are you ill? You look like you have the chills." It was Galabra, still in her night robe, looking concerned as a mother would over a sick child. "No," I said, " Just a bad dream."
** SellSword
** Story of William the Gray
*** Beginning
I was not born into a wealthy family, but neither were we poor. My father worked as a blacksmith, and my mother an alchemist. My father's youngest brother, my Uncle Girard, worked as a Trainer. Trainers in our community were men and women, mostly men, who trained our village how to fight. These were the men and women who also led us, when it was necessary, to defend against military incursions, which hadn't happened to us in over a century or so, and also against organized bandits, which were far more common. Most Trainers worked and farmed among us and would hold village musters for training at least twice a month. My Uncle Girard was a master swordsman. He was skilled with sword and shield, and being a bear of a man, the best wrestler in our village, perhaps even the best within our commonwealth.
*** Adolescence
*** Trade
